[project]
name = "balatrollm"
version = "0.2.0"
description = "LLM-powered bot that plays Balatro using strategic decision making"
readme = "README.md"
authors = [{ name = "S1M0N38", email = "bertolottosimone@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
  "balatrobot",
  "jinja2>=3.1.6",
  "openai>=1.99.3",
  "litellm[proxy]>=1.74.0",
  "httpx>=0.27.0",
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/S1M0N38/balatrollm"
Issues = "https://github.com/S1M0N38/balatrollm/issues"
Repository = "https://github.com/S1M0N38/balatrollm"
Changelog = "https://github.com/S1M0N38/balatrollm/blob/main/CHANGELOG.md"

[project.scripts]
balatrollm = "balatrollm:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
publish-url = "https://upload.pypi.org/legacy/"

[tool.uv.sources]
balatrobot = { git = "https://github.com/S1M0N38/balatrobot.git", rev = "main" }

[tool.ruff]
exclude = [".venv", "balatrobot", "balatro"]
lint.extend-select = ["I"]
lint.task-tags = ["FIX", "TODO", "HACK", "WARN", "PERF", "NOTE", "TEST"]

[tool.pyright]
typeCheckingMode = "basic"

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
  "basedpyright>=1.31.1",
  "pytest>=8.4.1",
  "pytest-asyncio>=1.1.0",
  "pytest-cov>=6.0.0",
  "ruff>=0.12.8",
]
