[project]
name = "balatrollm"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "S1M0N38", email = "bertolottosimone@gmail.com" }]
requires-python = ">=3.13"
dependencies = []
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/S1M0N38/balatrollm"
Issues = "https://github.com/S1M0N38/balatrollm/issues"
Repository = "https://github.com/S1M0N38/balatrollm"
Changelog = "https://github.com/S1M0N38/balatrollm/blob/main/CHANGELOG.md"

[project.scripts]
balatrollm = "balatrollm:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
publish-url = "https://upload.pypi.org/legacy/"

[tool.ruff]
lint.extend-select = ["I"]
lint.task-tags = ["FIX", "TODO", "HACK", "WARN", "PERF", "NOTE", "TEST"]

[tool.pyright]
typeCheckingMode = "basic"

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
  "basedpyright>=1.31.1",
  "pytest>=8.4.1",
  "pytest-asyncio>=1.1.0",
  "ruff>=0.12.8",
]
