model_list:
  - model_name: openai/gpt-oss-120b
    litellm_params:
      model: openrouter/openai/gpt-oss-120b
  - model_name: openai/gpt-oss-20b
    litellm_params:
      model: openrouter/openai/gpt-oss-20b
  - model_name: qwen/qwen3-235b-a22b-thinking-2507
    litellm_params:
      model: openrouter/qwen/qwen3-235b-a22b-thinking-2507
  - model_name: qwen/qwen3-235b-a22b-2507
    litellm_params:
      model: openrouter/qwen/qwen3-235b-a22b-2507
  - model_name: x-ai/grok-code-fast-1
    litellm_params:
      model: openrouter/x-ai/grok-code-fast-1
  - model_name: google/gemini-2.5-flash
    litellm_params:
      model: openrouter/google/gemini-2.5-flash
  - model_name: google/gemini-2.5-flash
    litellm_params:
      model: openrouter/google/gemini-2.5-flash
router_settings:
  default_litellm_params:
    api_key: os.environ/OPENROUTER_API_KEY
    reasoning:
      effort: "medium"
    usage:
      include: True
    provider:
      sort: "price"
    seed: 0
general_settings:
  master_key: sk-balatrollm-proxy-key
  set_verbose: true
