models:
  - model: openai/gpt-oss-120b
    extra_body:
      reasoning:
        effort: medium
  - model: openai/gpt-oss-20b
    extra_body:
      reasoning:
        effort: medium
  - model: qwen/qwen3-235b-a22b-thinking-2507
  - model: qwen/qwen3-235b-a22b-2507
  - model: deepseek/deepseek-chat-v3.1
    extra_body:
      reasoning:
        effort: medium
  - model: x-ai/grok-4-fast:free
    extra_body:
      reasoning:
        effort: medium
  - model: google/gemini-2.5-pro
    extra_body:
      reasoning:
        effort: medium
  - model: google/gemini-2.5-flash
    extra_body:
      reasoning:
        effort: medium
  - model: anthropic/claude-sonnet-4
    extra_body:
      reasoning:
        effort: medium
  - model: openai/gpt-5
    extra_body:
      reasoning:
        effort: medium
defaults:
  seed: 1
  parallel_tool_calls: false
  tool_choice: auto
  extra_headers:
    HTTP-Referer: https://github.com/S1M0N38/balatrollm
    X-Title: BalatroLLM
  extra_body:
    provider:
      order: ['cerebras']
      sort: price
    usage:
      include: true
