models:
  # Qwen
  - model: qwen/qwen3-30b-a3b-thinking-2507
  - model: qwen/qwen3-next-80b-a3b-thinking
  - model: qwen/qwen3-235b-a22b-thinking-2507
  - model: qwen/qwen3-max
  # Deepseek
  - model: deepseek/deepseek-v3.2-exp
  # X-AI
  - model: x-ai/grok-4-fast
  - model: x-ai/grok-4
  # Google
  - model: google/gemini-2.5-flash-lite
  - model: google/gemini-2.5-flash
  - model: google/gemini-2.5-pro
  # Anthropic
  - model: anthropic/claude-haiku-4.5
  - model: anthropic/claude-sonnet-4.5
  - model: anthropic/claude-opus-4.1
  # OpenAI
  - model: openai/gpt-oss-20b
  - model: openai/gpt-oss-120b
  - model: openai/gpt-5-nano
  - model: openai/gpt-5-mini
  - model: openai/gpt-5
defaults:
  seed: 1
  parallel_tool_calls: false
  tool_choice: auto
  extra_headers:
    HTTP-Referer: https://github.com/coder/balatrollm
    X-Title: BalatroLLM
  extra_body:
    reasoning:
      effort: medium
    provider:
      order: ['cerebras']
      sort: throughput
    usage:
      include: true
